//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C4_Persistencia.FabricaDAO {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Parametros : global::System.Configuration.ApplicationSettingsBase {
        
        private static Parametros defaultInstance = ((Parametros)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Parametros())));
        
        public static Parametros Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C4_Persistencia.DAO.FabricaDAOSQL")]
        public string claseFabricaDAO {
            get {
                return ((string)(this["claseFabricaDAO"]));
            }
        }
    }
}
